---

- hosts: all
  become: yes
  become_method: sudo
  tasks:
  - name: Install MySQL packages
    apt: pkg={{item}} state=installed
    with_items:
      - bundler
      - mysql-server-core-5.5
      - mysql-client-core-5.5
      - libmysqlclient-dev
      - python-mysqldb
      - mysql-server
      - mysql-client
      - build-essential
  - name: Remove the MySQL test database
    action: mysql_db db=test state=absent

  - name: Set root password
    mysql_user: name=root password=aqwe123 host="{{item}}" priv=*.*:ALL,GRANT state=present
    with_items:
      - "{{ansible_hostname}}"
      - 127.0.0.1
      - ::1
      - localhost
      
  - name: Restart the MySQL service
    action: service name=mysql state=restarted enabled=true

  - name: Create Dir to Downlaod Tomcat. 
    file: path=/opt/SP/apps/tomcat state=directory

  - name: Install Java 1.8 
    apt: name=default-jdk state=present

  - name: Download Tomcat
    get_url: url=http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz dest=/opt/SP/apps/tomcat.tar.gz mode=0755 

  - name: Extract Tomcat
    command: "tar zxf /opt/SP/apps/tomcat.tar.gz  -C /opt/SP/apps/tomcat --strip-components 1"
   
  - name: Copy Petclinic Project War Files
    copy: src=target/kalingamusic-0.0.1-SNAPSHOT.war dest=/opt/SP/apps/tomcat/webapps/ mode=0644
    notify: 
    - Restart Tomcat
    
  handlers:
  - name: Restart Tomcat
    shell: "nohup sh /opt/SP/apps/tomcat/bin/catalina.sh start" 
